# Site settings
title: "Title"
author: "Adam Jabłoński" 
email: "adjablon@gmail.com" 
description: "Description"
baseurl: ""
url: "http://adjablon.github.io"

# Build settings
markdown: kramdown
permalink: pretty
